### ISSUE TITLE
Update pinned pandas package 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#591]
Works correctly with `1.0.3` but the current pinned package fails with:
https://github.com/OasisLMF/OasisLMF/blob/master/requirements-package.in#L13

```
2020-06-10 16:57:35,047 - root - ERROR - Exception raised in 'get_gul_input_items', TypeError: visit_Constant() got an unexpected keyword argument 'side'
Traceback (most recent call last):
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/oasislmf/model_preparation/gul_inputs.py", line 222, in get_gul_input_items
    exposure_df.query(query_nonzero_tiv, inplace=True, engine='numexpr')
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/frame.py", line 3184, in query
    res = self.eval(expr, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/frame.py", line 3300, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 322, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env, truediv=truediv)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 827, in __init__
    self.terms = self.parse()
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 844, in parse
    return self._visitor.visit(self.expr)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 441, in visit
    return visitor(node, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 447, in visit_Module
    return self.visit(expr, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 441, in visit
    return visitor(node, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 450, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 441, in visit
    return visitor(node, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 771, in visit_BoolOp
    return reduce(visitor, operands)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 764, in visitor
    lhs = self._try_visit_binop(x)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 760, in _try_visit_binop
    return self.visit(bop)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 441, in visit
    return visitor(node, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 744, in visit_Compare
    return self.visit(binop)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 441, in visit
    return visitor(node, **kwargs)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 563, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 484, in _maybe_transform_eq_ne
    right = self.visit(node.right, side="right")
  File "/home/sam/repos/venv/api/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 441, in visit
    return visitor(node, **kwargs)
TypeError: visit_Constant() got an unexpected keyword argument 'side'
```
